//import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "./component/bootstrapClient"
//import "./globals.css";
import "./css/bootstrap.min.css";
import "./css/style.css";

import Navebar from "./component/navebar"
import Header from "./component/header"
import Footer from "./component/footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header/>
      <body>
        <Navebar/>
        {children}
        <Footer/>
        <BootstrapClient/>
      </body>
    </html>
  );
}
